### ISSUE TITLE
 Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices.

### ISSUE THREAD

**Issue by matthewboogie** [ParthK117/etn-ez-miner#1]
Using AMD GPU. Tried changing the config but it keeps changing it back to default.

**Comment by ParthK117** [comment]
Are you sure that you've selected AMD as your gpu brand?
I've attached a .mcf file I've preconfigured for you, try using it and see if it begans mining.
[amd.zip](https://github.com/ParthK117/etn-ez-miner/files/1545197/amd.zip)
Make sure to extract the zip file and load the configuration from within the miner.
Take care to use your own wallet address!

**Comment by ParthK117** [comment]
It's been over a week, I'll assume that your miner is configured incorrectly. Open a new issue if this is not the case.
