### ISSUE TITLE
Auto Restart Miner

### ISSUE THREAD

**Issue by Nexus237** [ParthK117/etn-ez-miner#2]
I remember in the previous version that, whenever a miner closes, it automatically restarts them ( i might be wrong). But its not there in the current version.

**Comment by ParthK117** [comment]
If you mean that the miner restarts on its own even after being terminated, that was never a feature, if you did experience that happening then it was a bug and was fixed in a later version. I'm quite sure what you mean by automatically restart though, can you clarify?

**Comment by ParthK117** [comment]
It's been over a week, open another issue if you are still having problems.
